name: dotnet Finance API CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore ./src/Finance.sln
    - name: Build
      run: dotnet build --no-restore ./src/Finance.sln
    - name: Test
      run: dotnet test --no-build --verbosity normal ./src/Finance.sln
    - name: Build and Push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v5.6
      with:
        image: gabrieljunio/finance-api
        tags: v1
        registry: ghcr.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        addLatest: true
