name: .NET CI Heroku

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore ./Finance.sln
    - name: Build
      run: dotnet build --no-restore ./Finance.sln
    - name: Test
      run: dotnet test --no-build --verbosity normal ./Finance.sln
  
  docker:
    runs-on: ubuntu-latest

    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: gabrieljunio/finance-api:latest

  deploy:
    name: Deploy into Heroku Account
    runs-on: ubuntu-latest

    environment: finance-prod
    steps:
      - name: App Settings Variable Substitution
        uses: microsoft/variable-substitiuion@v1
        with: 
          files: 'appsettings.json'
        env:
          ConnectionStrings.DefaultConnection: ${{ secrets.POSTGRES_CONNECTION }}
          AppSettings: ${{ secrets.APP_SETTINGS }}
      - name: Deploying into Heroku
        uses: AkhileshNS/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_API_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          usedocker: true


